<?php
/**
 * @file
 * Code for the DKAN Featured Topics feature.
 */

include_once 'dkan_featured_topics.features.inc';

/**
 * Implements hook_page_alter().
 */
function dkan_featured_topics_page_alter(&$page) {
   drupal_add_css(drupal_get_path('module', 'dkan_featured_topics') . '/dkan_featured_topics.css');
}

/**
 * Implements hook_theme_registry_alter().
 */
function dkan_featured_topics_theme_registry_alter(&$theme_registry) {
  $theme_registry['menu_link__main_menu']['function'] = 'dkan_featured_topics_main_menu';
}

/**
 * Overrides theme_main_menu() to add topics dropdown.
 */
function dkan_featured_topics_main_menu($variables) {
  $output = '<li>';
  if ($variables['element']['#title'] == t('Topics')) {
    $link = ($variables['element']['#href'] == '<front>') ? '/' : $variables['element']['#href'];
    $output .= '<a href="' . $link . '" class="dropdown-toggle" data-toggle="dropdown" data-target="#"> ' . $variables['element']["#title"] . '<b class="caret"></b></a>';
    //$output .= views_embed_view('topics_list', 'block');
    $output .= views_embed_view('dkan_topics_featured', 'block_1');
  }
  else {
    $output .= l($variables['element']['#title'], $variables['element']['#href'], $variables['element']);
  }
  $output .= '</li>';
  return $output;
}
