<?php
/**
 * @file
 * Code for the DKAN Featured Topics feature.
 */

include_once 'dkan_featured_topics.features.inc';

/**
 * Adds "Topics" to main menu.
 */
function dkan_featured_topics_add_menu() {
  $main_menu = menu_load_links('main-menu');
  $topics_enabled = FALSE;
  foreach ($main_menu as $link) {
    if ($link['link_title'] == t('Topics')) {
      $topics_enabled = TRUE;
      break;
    }
  }
  if (!$topics_enabled) {
    $item = array(
      'link_path' => '<front>',
      'link_title' => t('Topics'),
      'menu_name' => 'main-menu',
      'weight' => 0,
      'plid' => 0,
      'module' => 'menu',
    );
    menu_link_save($item);
  }
}
